apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsrover
spec:
  replicas: 2
  selector:
    matchLabels:
      name: marsrover
  template:
    metadata:
      labels:
        name: marsrover
    spec:
      containers:
      - name: marsrover
        image: olliebatch/marsrover:0.0.1
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 1000Mi
        env:
        - name: SESSION_REDIS
          value: "true"
        ports:
        - containerPort: 5000