
apiVersion: v1
kind: Service
metadata:
  name: marsrover
  labels:
    name: marsrover
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 5000
  selector:
    name: marsrover
