
apiVersion: v1
kind: Service
metadata:
  name: marsRover
  labels:
    name: marsRover
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  selector:
    name: marsRover
